name: Github Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Installing Dependencies with Yarn
        run: yarn
      - name: Building Angular Project
        run: yarn build
      - name: Setup Git Config
        run: |
          git config --global user.email "ethereal97@gmail.com"
          git config --global user.name "SKM Etheloper"
      - name: Commit Git Changes
        run: |
          mv dist docs
          cp docs/index.html docs/404.html
          git checkout --orphan gh-pages
          git add --all
          git commit -m "Github Pages"
          git push origin gh-pages --force
